version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: weekly

  - package-ecosystem: "npm"
    directory: "/packages/cdk-app-cloudfront"
    schedule:
      interval: weekly

  - package-ecosystem: "npm"
    directory: "/packages/cdk-base-cf-acm-r53"
    schedule:
      interval: weekly

  - package-ecosystem: "npm"
    directory: "/packages/cdk-certificate"
    schedule:
      interval: weekly

  - package-ecosystem: "npm"
    directory: "/packages/cdk-cloudfront-behavior"
    schedule:
      interval: weekly

  - package-ecosystem: "npm"
    directory: "/packages/cdk-cloudfront-cache-policy"
    schedule:
      interval: weekly

  - package-ecosystem: "npm"
    directory: "/packages/cdk-cloudfront-origin-request-policy"
    schedule:
      interval: weekly

  - package-ecosystem: "npm"
    directory: "/packages/cdk-dynamodbtable"
    schedule:
      interval: weekly

  - package-ecosystem: "npm"
    directory: "/packages/cdk-ecs-alb"
    schedule:
      interval: weekly

  - package-ecosystem: "npm"
    directory: "/packages/cdk-ecs-codedeploy-resources"
    schedule:
      interval: weekly

  - package-ecosystem: "npm"
    directory: "/packages/cdk-ecs-nlb"
    schedule:
      interval: weekly

  - package-ecosystem: "npm"
    directory: "/packages/cdk-ecs-task-definition"
    schedule:
      interval: weekly

  - package-ecosystem: "npm"
    directory: "/packages/cdk-environment-resources"
    schedule:
      interval: weekly

  - package-ecosystem: "npm"
    directory: "/packages/cdk-files-bucket"
    schedule:
      interval: weekly

  - package-ecosystem: "npm"
    directory: "/packages/cdk-global-endpoints"
    schedule:
      interval: weekly

  - package-ecosystem: "npm"
    directory: "/packages/cdk-multi-account-dns"
    schedule:
      interval: weekly

  - package-ecosystem: "npm"
    directory: "/packages/cdk-pipeline"
    schedule:
      interval: weekly

  - package-ecosystem: "npm"
    directory: "/packages/cdk-route53-record"
    schedule:
      interval: weekly

  - package-ecosystem: "npm"
    directory: "/packages/cdk-s3-redirect"
    schedule:
      interval: weekly

  - package-ecosystem: "npm"
    directory: "/packages/cdk-shared-services-resources"
    schedule:
      interval: weekly

  - package-ecosystem: "npm"
    directory: "/packages/cdk-sns-topic"
    schedule:
      interval: weekly

  - package-ecosystem: "npm"
    directory: "/packages/cdk-static-website"
    schedule:
      interval: weekly