version: 0
Resources:
  - TargetService:
      Type: AWS::ECS::Service
      Properties:
        TaskDefinition: >-
          arn:aws:ecs:${Token[AWS.Region.9]}:${Token[AWS.AccountId.5]}:task-definition/test-test
        LoadBalancerInfo:
          ContainerName: Container
          ContainerPort: 80
