name: CDK Publishing
on:
  push:
    branches:
      - PLATFORM-v2-constructs
  
jobs:
  get-file-changes:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: dorny/paths-filter@v2
        id: api-gateway-domain
        with:
          filters: |
            packages/cdk-api-gateway-domain:
              - '/packages/cdk-api-gateway-domain/**'
      - uses: dorny/paths-filter@v2
        id: api-gateway-domain-multi-region
        with:
          filters: |
            packages/cdk-api-gateway-domain-multi-region:
              - '/packages/cdk-api-gateway-domain-multi-region/**'
      - uses: dorny/paths-filter@v2
        id: app-bucket
        with:
          filters: |
            packages/cdk-app-bucket:
              - '/packages/cdk-app-bucket/**'
      - uses: dorny/paths-filter@v2
        id: app-cloudfront
        with:
          filters: |
            packages/cdk-app-cloudfront:
              - '/packages/cdk-app-cloudfront/**'
      - uses: dorny/paths-filter@v2
        id: base-cf-acm-r53
        with:
          filters: |
            packages/cdk-base-cf-acm-r53:
              - '/packages/cdk-base-cf-acm-r53/**'
      - uses: dorny/paths-filter@v2
        id: certificate
        with:
          filters: |
            packages/cdk-certificate:
              - '/packages/cdk-certificate/**'
      # - uses: dorny/paths-filter@v2
      #   id: cloudfront-behavior
      #   with:
      #     filters: |
      #       packages/cdk-cloudfront-behavior:
      #         - '/packages/cdk-cloudfront-behavior/**'
      - uses: dorny/paths-filter@v2
        id: cloudfront-cache-policy
        with:
          filters: |
            packages/cdk-cloudfront-cache-policy:
              - '/packages/cdk-cloudfront-cache-policy/**'
      - uses: dorny/paths-filter@v2
        id: cloudfront-origin-request-policy
        with:
          filters: |
            packages/cdk-cloudfront-origin-request-policy:
              - '/packages/cdk-cloudfront-origin-request-policy/**'
      - uses: dorny/paths-filter@v2
        id: dynamodbtable
        with:
          filters: |
            packages/cdk-dynamodbtable:
              - '/packages/cdk-dynamodbtable/**'
      - uses: dorny/paths-filter@v2
        id: ecs-alb
        with:
          filters: |
            packages/cdk-ecs-alb:
              - '/packages/cdk-ecs-alb/**'
      - uses: dorny/paths-filter@v2
        id: ecs-codedeploy-resources
        with:
          filters: |
            packages/cdk-ecs-codedeploy-resources:
              - '/packages/cdk-ecs-codedeploy-resources/**'
      - uses: dorny/paths-filter@v2
        id: ecs-nlb
        with:
          filters: |
            packages/cdk-ecs-nlb:
              - '/packages/cdk-ecs-nlb/**'
      - uses: dorny/paths-filter@v2
        id: ecs-task-definition
        with:
          filters: |
            packages/cdk-ecs-task-definition:
              - '/packages/cdk-ecs-task-definition/**'
      - uses: dorny/paths-filter@v2
        id: environment-resources
        with:
          filters: |
            packages/cdk-environment-resources:
              - '/packages/cdk-environment-resources/**'
      - uses: dorny/paths-filter@v2
        id: files-bucket
        with:
          filters: |
            packages/cdk-files-bucket:
              - '/packages/cdk-files-bucket/**'
      - uses: dorny/paths-filter@v2
        id: multi-account-dns
        with:
          filters: |
            packages/cdk-multi-account-dns:
              - '/packages/cdk-multi-account-dns/**'
      - uses: dorny/paths-filter@v2
        id: pipeline
        with:
          filters: |
            packages/cdk-pipeline:
              - '/packages/cdk-pipeline/**'
      - uses: dorny/paths-filter@v2
        id: route53-record
        with:
          filters: |
            packages/cdk-route53-record:
              - '/packages/cdk-route53-record/**'
      - uses: dorny/paths-filter@v2
        id: s3-deployment
        with:
          filters: |
            packages/cdk-s3-deployment:
              - '/packages/cdk-s3-deployment/**'
      - uses: dorny/paths-filter@v2
        id: s3-redirect
        with:
          filters: |
            packages/cdk-s3-redirect:
              - '/packages/cdk-s3-redirect/**'
      - uses: dorny/paths-filter@v2
        id: shared-services-resources
        with:
          filters: |
            packages/cdk-shared-services-resources:
              - '/packages/cdk-shared-services-resources/**'
      - uses: dorny/paths-filter@v2
        id: sns-topic
        with:
          filters: |
            packages/cdk-sns-topic:
              - '/packages/cdk-sns-topic/**'
      # - uses: dorny/paths-filter@v2
      #   id: static-website
      #   with:
      #     filters: |
      #       packages/cdk-static-website:
      #         - '/packages/cdk-static-website/**'
  
  Build-test-and-publish:
    needs: get-file-changes
    runs-on: ubuntu-latest
    steps:
      - if: steps.api-gateway-domain.outputs.packages/cdk-api-gateway-domain == 'true'
        run: | 
          npm install
          npm run build
          npm run lint
          npm run test
          npm publish 
        working-directory: packages/cdk-api-gateway-domain
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      - if: steps.api-gateway-domain-multi-region.outputs.packages/cdk-api-gateway-domain-multi-region == 'true'
        run: | 
          npm install
          npm run build
          npm run lint
          npm run test 
          npm publish 
        working-directory: packages/cdk-api-gateway-domain-multi-region
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      - if: steps.app-bucket.outputs.packages/cdk-app-bucket == 'true'
        run: | 
          npm install
          npm run build
          npm run lint
          npm run test 
          npm publish 
        working-directory: packages/cdk-app-bucket
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      - if: steps.app-cloudfront.outputs.packages/cdk-app-cloudfront == 'true'
        run: | 
          npm install
          npm run build
          npm run lint
          npm run test
          npm publish 
        working-directory: packages/cdk-app-cloudfront
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      - if: steps.base-cf-acm-r53.outputs.packages/cdk-base-cf-acm-r53 == 'true'
        run: | 
          npm install
          npm run build
          npm run lint
          npm run test   
          npm publish 
        working-directory: packages/cdk-base-cf-acm-r53
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      - if: steps.certificate.outputs.packages/cdk-certificate == 'true'
        run: | 
          npm install
          npm run build
          npm run lint
          npm run test          
          npm publish 
        working-directory: packages/cdk-certificate
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      # - if: steps.cloudfront-behavior.outputs.packages/cdk-cloudfront-behavior == 'true'
      #   run: | 
      #     npm install
      #     npm run build
      #     npm run lint
      #     npm run test           
      #     npm publish 
      #   working-directory: packages/cdk-cloudfront-behavior
      #   env:
      #     NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      - if: steps.cloudfront-cache-policy.outputs.packages/cdk-cloudfront-cache-policy == 'true'
        run: | 
          npm install
          npm run build
          npm run lint
          npm run test           
          npm publish 
        working-directory: packages/cdk-cloudfront-cache-policy
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      - if: steps.cloudfront-origin-request-policy.outputs.packages/cdk-cloudfront-origin-request-policy == 'true'
        run: | 
          npm install
          npm run build
          npm run lint
          npm run test           
          npm publish 
        working-directory: packages/cdk-cloudfront-origin-request-policy
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      - if: steps.dynamodbtable.outputs.packages/cdk-dynamodbtable == 'true'
        run: | 
          npm install
          npm run build
          npm run lint
          npm run test 
          npm publish 
        working-directory: packages/cdk-dynamodbtable
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      - if: steps.ecs-alb.outputs.packages/cdk-ecs-alb == 'true'
        run: | 
          npm install
          npm run build
          npm run lint
          npm run test           
          npm publish 
        working-directory: packages/cdk-ecs-alb
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      - if: steps.ecs-codedeploy-resources.outputs.packages/cdk-ecs-codedeploy-resources == 'true'
        run: | 
          npm install
          npm run build
          npm run lint
          npm run test         
          npm publish 
        working-directory: packages/cdk-ecs-codedeploy-resources
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      - if: steps.ecs-nlb.outputs.packages/cdk-ecs-nlb == 'true'
        run: | 
          npm install
          npm run build
          npm run lint
          npm run test           
          npm publish 
        working-directory: packages/cdk-ecs-nlb
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      - if: steps.ecs-task-definition.outputs.packages/cdk-ecs-task-definition == 'true'
        run: | 
          npm install
          npm run build
          npm run lint
          npm run test           
          npm publish 
        working-directory: packages/cdk-ecs-task-definition
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      - if: steps.environment-resources.outputs.packages/cdk-environment-resources == 'true'
        run: | 
          npm install
          npm run build
          npm run lint
          npm run test           
          npm publish 
        working-directory: packages/cdk-environment-resources
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      - if: steps.files-bucket.outputs.packages/cdk-files-bucket == 'true'
        run: | 
          npm install
          npm run build
          npm run lint
          npm run test           
          npm publish 
        working-directory: packages/cdk-files-bucket
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      - if: steps.multi-account-dns.outputs.packages/cdk-multi-account-dns == 'true'
        run: | 
          npm install
          npm run build
          npm run lint
          npm run test           
          npm publish 
        working-directory: packages/cdk-multi-account-dns
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      - if: steps.pipeline.outputs.packages/cdk-pipeline == 'true'
        run: | 
          npm install
          npm run build
          npm run lint
          npm run test           
          npm publish 
        working-directory: packages/cdk-pipelin
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      - if: steps.route53-record.outputs.packages/cdk-route53-record == 'true'
        run: | 
          npm install
          npm run build
          npm run lint
          npm run test           
          npm publish 
        working-directory: packages/cdk-route53-record
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      - if: steps.s3-deployment.outputs.packages/cdk-s3-deployment == 'true'
        run: | 
          npm install
          npm run build
          npm run lint
          npm run test           
          npm publish 
        working-directory: packages/cdk-s3-deployment
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      - if: steps.s3-redirect.outputs.packages/cdk-s3-redirect == 'true'
        run: | 
          npm install
          npm run build
          npm run lint
          npm run test           
          npm publish 
        working-directory: packages/cdk-s3-redirect
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      - if: steps.shared-services-resources.outputs.packages/cdk-shared-services-resources == 'true'
        run: | 
          npm install
          npm run build
          npm run lint
          npm run test          
          npm publish 
        working-directory: packages/cdk-shared-services-resources
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      - if: steps.sns-topic.outputs.packages/cdk-sns-topic == 'true'
        run: | 
          npm install
          npm run build
          npm run lint
          npm run test          
          npm publish 
        working-directory: packages/cdk-sns-topic
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      # - if: steps.static-website.outputs.cdk-static-website == 'true'
      #   run: | 
      #     npm install
      #     npm run build
      #     npm run lint
      #     npm run test          
      #     npm publish 
      #   working-directory: packages/cdk-static-website
      #   env:
      #     NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
  
  # Slack-on-failure:
  #   if: always()
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v3
  #     - name: Send slack message
  #       uses: rtCamp/action-slack-notify@v2
  #       env:
  #         SLACK_CHANNEL: platform-alerts
  #         SLACK_COLOR: ${{ job.status }}
  #         SLACK_MESSAGE: 'Workflow was, ${{ job.status }}' 
  #         SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
